Repository CSC207-2022F-UofT/course-project-fixthewifi, pull requests merged in 2022-12, with the labels that each got.

#66 Feature profile
  User.csv
  src/main/java/client/frameworks_and_drivers/Constants.java
  src/main/java/client/frameworks_and_drivers/InputSorter.java
  src/main/java/client/frameworks_and_drivers/view/console_view/ConsoleView.java
  src/main/java/client/frameworks_and_drivers/view/console_view/InstructionSet.java
  src/main/java/client/interface_adapters/controllers/change_profile/ChPrController.java
  src/main/java/client/interface_adapters/controllers/change_profile/ChPrControllerInputBoundary.java
  src/main/java/client/interface_adapters/model/Model.java
  src/main/java/client/interface_adapters/model/model_entities/UserProfile.java
  src/main/java/client/interface_adapters/presenters/LoginPresenter.java
  src/main/java/client/interface_adapters/presenters/change_profile/ChPrPresenter.java
  src/main/java/client/interface_adapters/presenters/change_profile/ChPrPresenterInputBoundary.java
  src/main/java/database/userList.csv
  src/main/java/server/frameworks_and_drivers/ChangeProfileDB.java
  src/main/java/server/frameworks_and_drivers/Constants.java
  src/main/java/server/frameworks_and_drivers/InputSorter.java
  src/main/java/server/frameworks_and_drivers/database/DataAccess.java
  src/main/java/server/frameworks_and_drivers/database/Database.java
  src/main/java/server/frameworks_and_drivers/database/data_access/ChPrAccess.java
  src/main/java/server/interface_adapters/change_profile/ChangeProfileController.java
  src/main/java/server/interface_adapters/change_profile/ChangeProfileOutputAdapter.java
  src/main/java/tutorial/HelloWorld.java
  src/main/java/tutorial/HelloWorld2.java
Labels: enhancement

#64 Feature group chat
  README.md
  src/main/java/server/frameworks_and_drivers/Constants.java
  src/main/java/server/interface_adapters/create_gc/CreateGCController.java
  src/main/java/server/interface_adapters/create_gc/CreateGCOutputAdapter.java
  src/main/java/server/interface_adapters/retrieve_friendslist/RetrieveFriendsListController.java
  src/main/java/server/interface_adapters/retrieve_friendslist/RetrieveFriendsListOutputAdapter.java
  src/main/java/server/usecases/create_gc/CreateGCDBGateway.java
  src/main/java/server/usecases/create_gc/CreateGCInputData.java
  src/main/java/server/usecases/create_gc/CreateGCInteractor.java
  src/main/java/server/usecases/create_gc/CreateGCOutputData.java
  src/main/java/server/usecases/retrieve_friendslist/RetrieveFriendsListDBGateway.java
  src/main/java/server/usecases/retrieve_friendslist/RetrieveFriendsListInteractor.java
  src/main/java/server/usecases/retrieve_friendslist/RetrieveFriendsListOutputData.java
  src/test/java/test_interface_adapters/create_gc/CreateGCComManager.java
  src/test/java/test_interface_adapters/create_gc/TestCreateGCOutputAdapter.java
  src/test/java/test_interface_adapters/retrieve_friendslist/TestRetrieveFriendsListComManager.java
  src/test/java/test_interface_adapters/retrieve_friendslist/TestRetrieveFriendsListOutputAdapter.java
  src/test/java/test_usecases/create_gc/CreateGCDummyDatabase.java
  src/test/java/test_usecases/create_gc/TestCreateGroupChat.java
  src/test/java/test_usecases/retrieve_friendslist/RetrieveFriendsListTestDatabase.java
  src/test/java/test_usecases/retrieve_friendslist/TestRetrieveFriendsList.java
Labels: enhancement, Testing

#76 fixed duplicate constant
  src/main/java/server/frameworks_and_drivers/Constants.java
Labels: bug

#87 Andys Controller and InputBoundary
  src/main/java/client/interface_adapters/controllers/DeleteEditMsgController.java
  src/main/java/client/interface_adapters/controllers/DeleteEditMsgControllerInputBoundary.java
Labels: enhancement

#78 Feature group chat
  src/main/java/server/entities/ChatProfile.java
  src/main/java/server/interface_adapters/create_gc/CreateGCOutputAdapter.java
  src/main/java/server/usecases/create_gc/CreateGCDBGateway.java
  src/main/java/server/usecases/create_gc/CreateGCInputData.java
  src/main/java/server/usecases/create_gc/CreateGCInteractor.java
  src/main/java/server/usecases/create_gc/CreateGCOutputBoundary.java
  src/main/java/server/usecases/create_gc/CreateGCOutputData.java
  src/test/java/TestFriend/TestRequestFriend.java
  src/test/java/test_friend/DummyModel.java
  src/test/java/test_friend/TestRequestFriend.java
  src/test/java/test_friend/output.java
  src/test/java/test_interface_adapters/create_gc/TestCreateGCOutputAdapter.java
  src/test/java/test_usecases/create_gc/CreateGCDummyOutputAdapter.java
  src/test/java/test_usecases/create_gc/TestCreateGroupChat.java
  src/test/java/test_usecases/test_register/TestRegister.java
  testuser.csv
Labels: bug, enhancement, Priority
